### ISSUE TITLE
target="_blank" auf externe Toiletten-Lieferanten

### ISSUE THREAD

**Issue by ralfhauser** [wc-guide/wc-guide-pwa#18]
![image](https://user-images.githubusercontent.com/1681677/67195744-d061fe00-f3f9-11e9-8807-8bc5aacb42e2.png)

Könnte man da und auf "nette Toilette" gleich einen Link im neuen Tab öffnen ?

**Comment by Sonnenschauer** [comment]
Diese Angabe dient nur zur Unterscheidung der WC-Typen und ist der falsche Ort für Verlinkungen. Eurokey ist erwähnt und verlinkt auf der Partner-Seite und näher erklärt in den Fragen. Auch bestehen keine Seiten zu den individuellen Toiletten auf eurokey.ch, ansonsten könnte man dies in Betracht ziehen. "Nette Toilette" wird dezentral von jeder Stadt/Gemeinde selber verwaltet und so aktuell keine Verlinkung möglich.

**Comment by ralfhauser** [comment]
Re Eurokey (ich bin ein wenig ein Link-Maniac, wo immer einer platziert werden kann, tendiere ich dazu, das auch zu tun  ;)   )
