### ISSUE TITLE
"Edit in OSM" link doesn't differ between way and node

### ISSUE THREAD

**Issue by Sonnenschauer** [wc-guide/wc-guide-pwa#39]
The "edit in OSM" link leads always to a node, even it is "way" (building). For example instead of https://www.openstreetmap.org/way/463244180, it is currently https://www.openstreetmap.org/node/463244180.

**Comment by chnuessli** [comment]
Maybe @nico-martin can show me the path to the osm generated link and i can see an error in there.

**Comment by nico-martin** [comment]
Ich konnte den Fehler beheben. :https://github.com/wc-guide/wc-guide-temp-backend/commit/0bd47deb87b08d5af33384e8a9fa6f84e5c69bc6

**Comment by Sonnenschauer** [comment]
Funktioniert. Vielen Dank fürs Beheben!
