### ISSUE TITLE
Languages and pages are not visible, only in desktop view

### ISSUE THREAD

**Issue by Sonnenschauer** [wc-guide/wc-guide-pwa#43]
- Languages Select Field shows only german, no other languages are selectable
- Static pages (FAQ, Home etc.) are not visible

**Comment by nico-martin** [comment]
Ich kann das Problem nicht nachstellen. Könntest du mal alle gespeicherten Daten der Webseite im Browser löschen und die Seite neu laden?

**Comment by Sonnenschauer** [comment]
Hab alle Daten in Mac Firefox gelöscht inkl. Cookies, jedoch kein Einfluss. Effekt tritt auch bei Safari auf. Ein einfaches „Page not found“ links unten in der Ecke und interessanterweise ist auch der „Bearbeiten“-Link wieder zurück auf „Open in OpenStreetMap“, also Englisch und wahrscheinlich eine Default-Einstellung. In der Strings-Datei heisst dies jetzt ganz einfach „Bearbeiten“. Im Inspector bei Firefox wird der <head> Bereich grau angezeigt. Weiss nicht ob dies was bedeutet, bzw. ob manche Daten so nicht angezogen werden.

In Chrome funktioniert es interessanterweise, auch wenn ich dort Cache/Cookies lösche. Wie ist bei dir wenn du die Seite mit Firefox aufmachst?

**Comment by Sonnenschauer** [comment]
Habs bei einem anderen Gerät probiert. Dort tritt das Problem in Firefox und auch in Chrome auf. Scheint also wirklich ein Problem zu sein.
